/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --strict-vars=false` (hash: 77b858ace3a356db478b04bfb573034f)
interface __BaseEnv_Env {
	DB: D1Database;
	ASSETS: Fetcher;
	COLLECTOR_ENABLED: string;
	ACCESS_TEAM_DOMAIN: string;
	ACCESS_AUD: string;
	THE_ODDS_API_KEY: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./platform/worker");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "COLLECTOR_ENABLED" | "ACCESS_TEAM_DOMAIN" | "ACCESS_AUD" | "THE_ODDS_API_KEY">> {}
}
