import {test,before,after} from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {build} from 'esbuild';
import {Miniflare,convertV4MiniflareOptions} from 'miniflare';
let mf;
before(async()=>{const result=await build({entryPoints:['tests/adapter-worker.ts'],bundle:true,write:false,format:'esm',platform:'neutral',external:['node:*'],conditions:['workerd','worker','browser']});mf=new Miniflare(convertV4MiniflareOptions({workers:[{name:"test",modules:true,script:result.outputFiles[0].text,compatibilityDate:'2026-09-13',compatibilityFlags:['nodejs_compat'],d1Databases:{DB:'test'},bindings:{COLLECTOR_ENABLED:'false',ACCESS_TEAM_DOMAIN:'',ACCESS_AUD:''},assets:{directory:'dist',binding:'ASSETS',run_worker_first:true,routerConfig:{has_user_worker:true}}}]}));const d=await mf.getD1Database('DB');for(const sql of (await readFile('migrations/0001_documents.sql','utf8')).split(';').filter(s=>s.trim()))await d.prepare(sql).run();});
after(async()=>{await mf?.dispose();});
async function op(operation,collection,args){const r=await mf.dispatchFetch('http://localhost/test/db',{method:'POST',body:JSON.stringify({operation,collection,args})});assert.equal(r.status,200,r.status===200?'':await r.text());return r.json();}
test('D1 preserves IDs, replaces records, isolates collections and keeps cursor stable after deletes',async()=>{const ids=await op('add','a',[{x:1,old:true},{x:2},{x:3}]);const page=await op('list','a',{limit:2});assert.deepEqual(page.items.map(x=>x.id),ids.slice(0,2));await op('delete','a',[ids[0]]);const next=await op('list','a',{limit:2,nextToken:page.nextToken});assert.equal(next.items[0].id,ids[2]);assert.deepEqual(await op('update','a',[{id:ids[1],record:{x:4}}]),[true]);assert.equal((await op('get','a',[ids[1]]))[0].old,undefined);assert.deepEqual(await op('get','b',[ids[1]]),[null]);assert.deepEqual(await op('update','b',[{id:ids[1],record:{x:9}}]),[false]);});
test('request context isolates concurrent writes',async()=>{const ids=await Promise.all(Array.from({length:12},(_,i)=>op('add','parallel-'+i,[{i}])));for(let i=0;i<12;i++)assert.equal((await op('get','parallel-'+i,ids[i]))[0].i,i);});
test('public APIs use D1 and do not invent live data without collector',async()=>{for(const path of ['/api/_healthcheck','/api/migration/status','/api/sharp/movements?hours=72&minDrop=5']){const r=await mf.dispatchFetch('http://localhost'+path);assert.equal(r.status,200);const body=await r.json();if(path.includes('movements')){assert.deepEqual(body.items,[]);assert.equal(body.live,false);}}});
test('private data remains inaccessible with forged identity headers',async()=>{for(const path of ['/api/profile','/api/tracker','/api/beta/owner/responses']){const r=await mf.dispatchFetch('http://localhost'+path,{headers:{'Cf-Access-Authenticated-User-Email':'milos.sdlc@gmail.com','Cf-Access-Jwt-Assertion':'forged'}});assert.equal(r.status,401);}});
test('input validation and unknown routes preserve HTTP errors',async()=>{assert.equal((await mf.dispatchFetch('http://localhost/api/sharp/movements?minDrop=999')).status,400);assert.equal((await mf.dispatchFetch('http://localhost/api/unknown')).status,404);assert.equal((await mf.dispatchFetch('http://localhost/api/profile',{method:'POST',headers:{'Content-Type':'application/json',Origin:'https://evil.test'},body:'{}'})).status,403);});
test('scheduled collector is inert until explicitly enabled',async()=>{const worker=await mf.getWorker();await worker.scheduled({cron:'*/5 * * * *'});const d=await mf.getD1Database('DB');assert.equal((await d.prepare('SELECT count(*) AS n FROM collector_lock').first()).n,0);});

test('collector preserves opening price and queues real downward movement for closing',async()=>{const at=Date.now();const date=new Date(at).toISOString().slice(0,10);const feed={mode:'live',source:'Test provider',snapshotAt:at,fixtures:[{id:'fixture-test',homeTeam:'Home',awayTeam:'Away',league:'Test',commenceTime:at+3600000,quotes:[{bookmaker:'Pinnacle',home:2,draw:3,away:4,updatedAt:at}]}]};await op('collect','',feed);const stateCollection='sharp_state_v6:fixture-test';const historyCollection='sharp_history_v6:fixture-test:'+date;for(const collection of [stateCollection,historyCollection]){const page=await op('list',collection,{});for(const item of page.items){if(item.last)item.last.observedAt=at-300001;if(item.points)for(const point of item.points)point.observedAt=at-300001;await op('update',collection,[{id:item.id,record:item}]);}}feed.fixtures[0].quotes[0].home=1.8;await op('collect','',feed);const signals=await op('list','sharp_signals_v6:'+date,{});assert.equal(signals.items.length,1);assert.equal(signals.items[0].fromOdds,2);assert.equal(signals.items[0].toOdds,1.8);assert.equal(signals.items[0].dropPercent,10);const queue=await op('list','sharp_closing_pending_v43',{});assert.equal(queue.items[0].signalId,signals.items[0].id);});
