export type Classification='Exceptional'|'Strong'|'Developing'|'Noise';
export type Movement={id:string;source:string;event:string;competition:string;market:string;selection:string;opening:number;current:number;percent:number;duration:number;score:number;classification:Classification;detectedAt:number;timeline:{time:number;price:number}[]};
export const classify=(score:number):Classification=>score>=85?'Exceptional':score>=65?'Strong':score>=35?'Developing':'Noise';
export const scoreMovement=(percent:number,duration:number)=>Math.min(100,Math.round(Math.abs(percent)*4+Math.min(25,Math.abs(percent)/duration*40)));
const fixtures=[['Arsenal','Liverpool','Premier League'],['Bayern Munich','RB Leipzig','Bundesliga'],['Inter','Napoli','Serie A'],['Real Madrid','Villarreal','La Liga'],['Lyon','Monaco','Ligue 1'],['Dortmund','Frankfurt','Bundesliga'],['Brighton','Newcastle','Premier League'],['Milan','Roma','Serie A'],['Barcelona','Sevilla','La Liga'],['Lille','Marseille','Ligue 1']];
export const movements:Movement[]=Array.from({length:50},(_,i)=>{const group=i<10?0:i<25?1:i<40?2:3;const [home,away,competition]=fixtures[i%10];const opening=Number((2.2+(i%7)*.13).toFixed(2));const magnitude=[19,13,7,1.5][group]+(i%3)*.15;const current=Number((opening*(1+(i%4===3?1:-1)*magnitude/100)).toFixed(2));const percent=(current/opening-1)*100;const duration=[28,24,35,60][group]+i%3;const detectedAt=Date.UTC(2026,8,8,16,0)-i*3600000;const timeline=[0,.25,.5,.75,1].map((fraction,j)=>({time:detectedAt-duration*60000+duration*60000*fraction,price:j===0?opening:j===4?current:Number((opening+(current-opening)*[0,.12,.4,.7,1][j]).toFixed(2))}));const score=scoreMovement(percent,duration);return{id:'MS-DEMO-'+String(i+1).padStart(3,'0'),source:'Pinnacle (simulated)',event:home+' vs '+away,competition,market:i%2?'Match winner':'Total goals · Over 2.5',selection:i%2?home:'Over 2.5',opening,current,percent,duration,score,classification:classify(score),detectedAt,timeline}});
export const signed=(n:number)=>(n>0?'+':'')+n.toFixed(1)+'%';
export const stamp=(n:number)=>new Date(n).toISOString().slice(5,16).replace('T',' ')+' UTC';

