import { api } from '@appdeploy/client';
import { useEffect, useRef, useState } from 'react';
type ResponseItem={id:string;answers:Record<string,string>;updatedAt:number};
export default function OwnerReview(){
 const [open,setOpen]=useState(false),[items,setItems]=useState<ResponseItem[]>([]),[cursor,setCursor]=useState<string|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[loaded,setLoaded]=useState(false),[mode,setMode]=useState('All');
 const [allowed,setAllowed]=useState(false);const alive=useRef(true);useEffect(()=>{alive.current=true;api.get('/api/beta/owner-access').then(r=>{if(alive.current)setAllowed(r.data.allowed===true)}).catch(()=>{if(alive.current)setAllowed(false)});return()=>{alive.current=false}},[]);
 async function load(more=false){setBusy(true);setError('');try{const r=await api.get('/api/beta/owner/responses',more&&cursor?{cursor}:{});if(!alive.current)return;setItems(old=>{const merged=new Map<string,ResponseItem>((more?old:[]).map(x=>[x.id,x]));for(const item of r.data.items as ResponseItem[])merged.set(item.id,item);return [...merged.values()].sort((a,b)=>b.updatedAt-a.updatedAt)});setCursor(r.data.nextToken||null);setLoaded(true)}catch{if(alive.current){setItems([]);setLoaded(false);setCursor(null);setError('Responses could not be loaded. Your owner sign-in may have expired. Sign in again or retry.')}}finally{if(alive.current)setBusy(false)}}
 const visible=items.filter(x=>mode==='All'||x.answers.mode===mode);
 function download(){const url=URL.createObjectURL(new Blob([JSON.stringify({exportedAt:new Date().toISOString(),scope:'Loaded responses only',moreAvailable:!!cursor,mode,items:visible},null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='marginscan-beta-feedback.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
 if(!allowed)return null;
 return <section className='faqcard beta-readiness'><h2>Owner review</h2><button className='primary' aria-expanded={open} onClick={()=>{setOpen(!open);if(!open&&!loaded)void load()}}>{open?'Close owner review':'Review beta responses'}</button>{open&&<div><p>Latest saved answers from indexed questionnaires. Earlier answers appear after the tester saves again. Counts and exports cover loaded responses only.</p><button disabled={busy} onClick={()=>void load()}>Refresh responses</button>{error&&<p role='alert'>{error}</p>}{busy&&<p role='status'>Loading responses…</p>}{loaded&&<><label>Data mode<select value={mode} onChange={e=>setMode(e.target.value)}>{['All','Demo','Live','Both','Unsure'].map(m=><option key={m}>{m}</option>)}</select></label><p>{visible.length} matching responses · {items.length} loaded{cursor?' · more available':''}</p><button disabled={busy||!visible.length} onClick={download}>Export shown responses (JSON)</button>{!visible.length&&<p>No matching responses loaded. This does not include older questionnaires that have not been saved again.</p>}{visible.map(item=><article key={item.id} style={{borderTop:'1px solid #52617a',marginTop:20,paddingTop:16,overflowWrap:'anywhere'}}><h3>Response {item.id.slice(-8)}</h3><small>Saved {new Date(item.updatedAt).toLocaleString()}</small><dl>{Object.entries({understanding:'Product understanding',alerts:'Strong Move alerts',clarity:'Product clarity',signalClarity:'Signal clarity',usefulness:'Usefulness',frequency:'Expected usage',pay:'Willingness to pay',mode:'Data mode',outcome:'Session outcome',price:'Monthly price (EUR)',missing:'Missing information',feature:'Valuable feature'}).map(([key,label])=><div key={key}><dt><b>{label}</b></dt><dd style={{margin:'4px 0 12px',whiteSpace:'pre-wrap'}}>{item.answers[key]||'Not answered'}</dd></div>)}</dl></article>)}{cursor&&<button className='primary' disabled={busy} onClick={()=>void load(true)}>Load more responses</button>}</>}</div>}</section>
}

